const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const summary = require('../daily-outlook-summary.js');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const date = '2026-10-05';
const item = { date, high: 76, low: 60, code: 61, precipProb: 95, dailyChanceKnown: true };
const amount = value => value.toFixed(1) + ' in';
function fixture() {
  return Array.from({ length: 24 }, (_, hour) => ({ date, hour, prob: 0, amount: 0, code: 0, temp: 70, feels: 70, wind: 5, gust: 10 }));
}
function edit(rows, hours, values) { for (const hour of hours) Object.assign(rows[hour], values); }
const rain = fixture();
edit(rain, [8,9], { prob: 45, amount: .05, code: 61 });
edit(rain, [18,19], { prob: 90, amount: .1, code: 61 });
const detail = summary.hourly(rain, item, 1, 'google', amount);
assert.equal(detail.rainTiming, '8 AM–10 AM · 6 PM–8 PM');
assert.match(detail.title, /Separate rain windows/);
assert.match(detail.copy, /break/);
assert.equal(detail.dailyChance, '95%');
assert.equal(detail.peakChance, '90% from 6 PM to 7 PM');
assert.equal(detail.peakChanceLabel, 'Peak hourly chance');
assert(!detail.copy.includes('95%') && !detail.copy.includes('76°'), 'overview does not repeat data boxes');
assert(!detail.copy.includes('focused from'), 'first-window/whole-day peak contradiction removed');
const broad = summary.hourly(rain, item, 10, 'visual-crossing', amount);
assert(!/AM|PM|\d/.test(broad.rainTiming), 'long-range timing stays broad');
assert(!/AM|PM/.test(broad.peakChance));
const missing = fixture(); edit(missing, [9], { prob: null, amount: null, wind: null, gust: null });
const incomplete = summary.hourly(missing, { ...item, precipProb: null, dailyChanceKnown: false }, 1, 'open-meteo', amount);
assert.equal(incomplete.dailyChance, 'Unavailable');
assert.match(incomplete.expectedRain, /Unavailable/);
assert(!/No meaningful precipitation window/.test(incomplete.rainTiming), 'missing values are not dry hours');
assert.match(incomplete.copy, /incomplete|missing/i);
const partial = summary.hourly(rain.slice(0, 12), item, 1, 'google', amount);
assert.match(partial.expectedRain, /At least/);
assert.match(partial.peakChance, /available hours/);
assert.equal(partial.rainTotal, null, 'partial amount is not a complete daily total');
const unknown = fixture().map(row => ({ ...row, prob: null, amount: null, code: null, wind: null, gust: null }));
const empty = summary.hourly(unknown, { ...item, precipProb: null }, 1, 'google', amount);
assert.equal(empty.peakChance, 'Unavailable'); assert.equal(empty.wind, 'Unavailable');
assert(!/dry|Little or none/.test(empty.rainTiming + empty.expectedRain));
assert.equal(summary.hourly([], item, 1, 'google', amount), null);
const duplicate = summary.hourly([...rain, { ...rain[8] }], item, 1, 'google', amount);
assert.equal(duplicate.expectedRain, detail.expectedRain, 'duplicate provider hour does not double the total');
const midnight = fixture(); edit(midnight, [23], { prob: 80, amount: .1, code: 61 });
assert.match(summary.hourly(midnight, item, 1, 'google', amount).rainTiming, /ending uncertain/);
const carryover = [...midnight, { date: '2026-10-06', hour: 0, prob: 80, amount: .1, code: 61, wind: 5, gust: 10 }];
assert.match(summary.hourly(carryover, item, 10, 'open-meteo', amount).rainTiming, /following day/);
const mixed = fixture(); edit(mixed, [9,10], { gust: 35, wind: 22 }); edit(mixed, [18,19], { prob: 90, amount: .1, code: 95 });
const mix = summary.hourly(mixed, item, 1, 'google', amount);
assert.match(mix.copy, /wind period comes before the storm period/);
assert.match(mix.wind, /Gusts up to 35 mph.*Sustained up to 22 mph/);
assert.equal(mix.windTiming, '9 AM–11 AM');
for (const code of [66, 73]) {
  const winter = fixture(); edit(winter, [9,10], { prob: 90, amount: .1, code, temp: 28 });
  const result = summary.hourly(winter, { ...item, code }, 1, 'google', amount);
  assert.equal(result.amountLabel, 'Liquid equivalent');
  assert.match(result.accumulationNote, /cannot be inferred/);
}
const parts = { ...item, dayParts: { daytime: { probability: 75, amount: .2, wind: 5, gust: 10 }, nighttime: { probability: 80, amount: .4, wind: 15, gust: 30 } } };
const gp = summary.googleParts(parts, 5, amount);
assert.equal(gp.peakChanceLabel, 'Day/night chances');
assert.equal(gp.peakChance, 'Day: 75% · Night: 80%');
assert.equal(gp.rainTiming, 'Daytime and night after this date');
assert.equal(gp.dailyChance, '95%');
assert(!gp.copy.includes('95%') && !gp.copy.includes('76°'));
const partialParts = summary.googleParts({ ...parts, dailyChanceKnown: false, dayParts: { daytime: parts.dayParts.daytime } }, 5, amount);
assert.match(partialParts.expectedRain, /Unavailable/);
assert.match(partialParts.peakChance, /Night: unavailable/);
assert.match(partialParts.copy, /missing/);
const dryParts = summary.googleParts({ ...item, precipProb: 0, code: 0, dayParts: { daytime: { probability: 0, amount: 0 }, nighttime: { probability: 0, amount: 0 } } }, 5, amount);
assert.equal(dryParts.expectedRain, 'Little or none');
assert.equal(dryParts.rainTiming, 'No meaningful precipitation window');
function extract(name) {
  const start = html.search(new RegExp('^    (?:async )?function ' + name + '\\(', 'm'));
  const tail = html.slice(start), end = tail.indexOf('\n    }');
  assert(start >= 0 && end >= 0, name);
  return tail.slice(0, end + 6);
}
const c = { DailyOutlookSummary: summary, Date, Number, Object, formatRainAmount: amount,
  visualCrossingCode: text => String(text || '').includes('rain') ? 61 : 0, codeToLabel: () => 'Clear', MM_PER_INCH: 25.4 };
vm.createContext(c);
for (const name of ['combineVisualCrossingDate', 'normalizeVisualCrossingForecast', 'precipitationInches', 'googleDayPartDetails', 'hourlyRecordsForDate', 'dailyDetailFromHourly', 'dailyDetailFromGoogleParts', 'forecastChangeText']) vm.runInContext(extract(name), c);
const raw = { days: [{ datetime: date, tempmax: 76, tempmin: 60, hours: [{ datetime: '09:00:00', temp: 70 }] }] };
const normalized = c.normalizeVisualCrossingForecast(raw);
const adapted = c.hourlyRecordsForDate(normalized, date);
assert.equal(adapted[0].prob, null); assert.equal(adapted[0].amount, null);
assert.equal(normalized.hourly.precipitation[0], 0, 'existing core/mini-card arrays unchanged');
assert.equal(c.googleDayPartDetails({}).probability, null);
assert.equal(c.precipitationInches({}), null);
assert.equal(c.precipitationInches({ qpf: { quantity: 25.4, unit: 'MILLIMETERS' } }), 1);
assert.equal(c.precipitationInches({ qpf: { quantity: 0, unit: 'INCHES' } }), 0);
assert.equal(c.hourlyRecordsForDate({ source: 'open-meteo', hourly: { time: [date + 'T09:00:00'] } }, date)[0].prob, null);
assert.equal(c.dailyDetailFromHourly(rain, item, 1, 'google').peakChance, detail.peakChance);
assert.equal(c.dailyDetailFromGoogleParts(parts, 5).peakChance, gp.peakChance);
assert(c.forecastChangeText({ detail: { summaryVersion: 2 } }, { detail: {} }).includes('analysis was updated'));
assert(html.includes('cached.detailVersion === 1'), 'valid cache is not invalidated to force new API requests');
assert(!extract('showDailyDetail').includes('fetch('), 'opening popup does not download data');
assert(/offset <= 15/.test(html));
async function integration() {
  const elements = ['dailyDetailOverlay', 'dailyDetailDate', 'dailyDetailTitle', 'dailyDetailCopy', 'dailyDetailGrid', 'dailyDetailChangeCopy', 'dailyDetailChange', 'dailyDetailMeta', 'dailyDetailCloseBtn'];
  c.els = Object.fromEntries(elements.map(name => [name, { textContent: '', innerHTML: '', classList: { remove() {}, toggle() {}, contains: () => false }, focus() {} }]));
  c.document = { activeElement: null }; c.syncModalScrollLock = () => {};
  c.dailySourceLabel = value => value; c.dailyDetailReturnFocus = null;
  vm.runInContext(extract('escapeHtml'), c);
  vm.runInContext(extract('showDailyDetail'), c);
  c.showDailyDetail({ ...item, source: 'google', detail, updatedAt: new Date().toISOString() });
  assert(c.els.dailyDetailGrid.innerHTML.includes('Daily chance'));
  assert(c.els.dailyDetailGrid.innerHTML.includes('Peak hourly chance'));
  assert(c.els.dailyDetailGrid.innerHTML.includes('95%') && c.els.dailyDetailGrid.innerHTML.includes('90% from'));
  c.showDailyDetail({ ...item, source: 'google', detail: { title: 'Old cached popup', copy: 'Old interpretation' } });
  assert(c.els.dailyDetailCopy.textContent.includes('next normal outlook refresh'), 'old cached interpretations are not presented as new analysis');
  assert(!c.els.dailyDetailGrid.innerHTML.includes('near 6 PM'));
  const saved = { value: [{ ...item, detail: { title: 'Legacy' } }], detailVersion: 1, localDate: 'today', updatedAt: new Date().toISOString() };
  c.DAILY_OUTLOOK_CACHE_KEY = 'cache'; c.DAILY_OUTLOOK_TTL_MS = 21600000;
  c.loadStorageMap = () => ({ loc: saved }); c.googleRainLocationKey = () => 'loc'; c.localDateKey = () => 'today';
  let requests = 0;
  c.getGoogleDailyForecast = () => { requests++; throw Error('must not fetch'); };
  vm.runInContext(extract('fetchDailyOutlook'), c);
  assert.strictEqual(await c.fetchDailyOutlook(33, -84, {}), saved.value);
  assert.equal(requests, 0, 'valid legacy cache retained with zero new downloads');
  c.weatherApiKey = () => 'test-key'; c.URLSearchParams = URLSearchParams; c.googleDisplayDateTimeValue = () => new Date(date + 'T00:00:00Z');
  c.fetchWeatherData = async () => {
    requests++;
    return { ok: true, json: async () => ({ forecastHours: [{ displayDateTime: { year: 2026, month: 10, day: 5, hours: requests - 1 } }], nextPageToken: 'next' }) };
  };
  vm.runInContext(extract('getGoogleHourlyDetailForecast'), c);
  const google = await c.getGoogleHourlyDetailForecast(33, -84);
  assert.equal(requests, 4, 'same four-page Google hourly limit, using fake responses');
  assert.equal(google[0].prob, null); assert.equal(google[0].amount, null); assert.equal(google[0].code, null);
  assert.equal(google[0].wind, null); assert.equal(google[0].gust, null);
  console.log('Daily popup checks passed: multiple windows, daily/hourly separation, missing/partial coverage, conservative endings, mixed weather, winter liquid equivalent, Google day/night summaries, adapters, rendering, cache preservation, and unchanged hourly request limit. No API requests.');
}
integration().catch(error => { console.error(error); process.exitCode = 1; });
